### ISSUE TITLE
Dante Virtual Soundcard

### ISSUE THREAD

**Issue by swalcott1** [eiz/SynchronousAudioRouter#8]
Hi:

i'm not a programmer, i'm a semi-ignorant recording engineer.  i'm bringing multi-channel audio from a macbook to a windows 7 pc using dante virtual sound card.

i can bring the audio into my daw but i can't monitor it/route it to my windows 7 sound card and i'm trying to using synchronous audio router to do that.  i'm trying to bring anywhere from 8-12 tracks of audio from the macbook into the pc and monitor each track in my daw software.  is this a bad idea?  right now i can't see how to do this.

you've clearly explained that a playback channel goes into an asio input channel but i'm having trouble envisioning how to get the virtual sound card connected to the sound card outputs

it's a really cool app and i promise not get you bogged down in a million questions.

thanks,

steven walcott

**Comment by eiz** [comment]
I'm not really familiar with Dante at all, but the core design choice in SAR that allows it to be efficient and avoid clock drift is that it is linked to a single ASIO device. That means if you want to use SAR with Dante's ASIO driver, you can't also use it with some local sound card on your machine at the same time, because the two are not clock-synchronized with one another. You would instead need to monitor through a Dante-enabled audio device, I think.

I've got some long term plans to integrate native networking support into SAR for multi-machine setups, but don't currently have time to work on it. You could try creating an aggregate interface using ASIO4ALL but my general feeling is that it will cause you nothing but pain and suffering due to the clock issues.

**Comment by swalcott1** [comment]
hey mackenzie:

thanks a whole bunch for getting back to me.
i somewhat concluded the same in a much lower iq fashion but it's good to
get confirmation from the software creator.

i tried to make an aggregate device, but for some reason dante soundcard
won't aggregate.

anyway, that's my problem and thanks again for writing the code and getting
back to me.

steven
