### ISSUE TITLE
Admin rights ?

### ISSUE THREAD

**Issue by Ulf3000** [eiz/SynchronousAudioRouter#9]
can you please make a version without the administrator rights needed ? 

starting your daw in admin mode  you can´t drag n drop files to or from the daw. it also makes other things complicated , otherwise awesome software though !

**Comment by eiz** [comment]
I haven't done this to date for 2 security related reasons:

- It would allow unprivileged applications to create Windows Audio devices
- Because of the way SAR implements low latency IO (direct mapping WaveRT registers and buffers between applications) it's theoretically possible for a malicious application to achieve privilege escalation in audiodg or another exclusive mode kernel streaming client using it, if that application doesn't properly validate the WaveRT register values.

It's simply a matter of changing the device ACL in the installer to make it work for any user. There's a really awful way to do this manually if you want:

- Download PsExec from here: https://technet.microsoft.com/en-us/sysinternals/pxexec.aspx
- Download the attached utility, [SecDescTool.zip](https://github.com/eiz/SynchronousAudioRouter/files/707031/SecDescTool.zip)
- Open an Administrator command prompt
- Run both C:\Windows\regedit.exe and C:\Full\Path\To\SecDescTool.exe with psexec -d -i -s, e.g. `psexec -d -i -s C:\Windows\regedit.exe` and `psexec -d -i -s C:\Users\eiz\Desktop\SecDescTool.exe`
- Enter the following string into SecDescTool: `D:P(A;;GA;;;AU)` and click Copy Binary
- Locate the SAR device entry in your PnP tree, it'll be in a subkey of HKLM\SYSTEM\CurrentControlSet\Enum\ROOT\MEDIA, e.g. 0000 on my machine. Should be fairly obvious from the values inside.
- Add a new Binary Value called Security. Edit it and paste in the data from SecDescTool
- Reboot your machine

I don't currently have time to implement a sane option for this in the installer, but I'll consider doing so the next time I get around to actually doing a new release.

**Comment by eiz** [comment]
Fixed in e35bccacbd46f52d1e4791e1422856af26e7c7e5, will be included in 0.13 release.
